#
# Copyright (c) 2019 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at:
#
#     https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#   Red Hat, Inc. - initial API and implementation
#

name: JKube Windows Specific Tests

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 1 * * *' # Everyday at 1

env:
  JKUBE_REPOSITORY: https://github.com/eclipse/jkube.git
  JKUBE_REVISION: master
  JKUBE_DIR: jkube

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Get Windows Version > Used to retrieve specific Docker Image
        shell: cmd
        run: |
          ver
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Checkout JKube Repository
        run: |
          git clone $env:JKUBE_REPOSITORY
          cd $env:JKUBE_DIR
          git checkout $env:JKUBE_REVISION
      - name: Install JKube
        run: |
          cd $env:JKUBE_DIR
          mvn -f pom.xml -B -DskipTests clean install
      - name: Install and Run Integration Tests
        run: |
          cd $env:JKUBE_DIR
          $env:JKUBE_VERSION = (mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression='project.version' -q -DforceStdout) | Out-String
          cd ..
          mvn -B -PWindows clean verify -D'jkube.version'=$env:JKUBE_VERSION
